
package com.crio.qcalc;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

       System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        ScientificCalculator scalc = new ScientificCalculator();
        System.out.println(scalc.squareOf(5));
        double res = scalc.modulo(5,2);
        System.out.println("modulo :"+res);
        System.out.println(scalc.modulo_double(10.0,2.0));

        calc.add(4,5);
        calc.printResult();
        calc.subtract(7,4);
        calc.printResult();
        calc.clearResult();
        calc.printResult();
        calc.multiply(3,4);
        calc.printResult();
        calc.divide(10,2);
        calc.printResult();
    }
}



