
package com.crio.qcalc;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.qcalc;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

       System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        
        calc.add(4,5);
        calc.printResult();
        calc.subtract(7,4);
        calc.printResult();
        calc.clearResult();
        calc.printResult();
        calc.multiply(3,4);
        calc.printResult();
        calc.divide(10,2);
        calc.printResult();
    }
}

        System.out.println(new App().getGreeting());
    }
}


